//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpdater {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_en_US() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoUpdater.Language_en-US", typeof(Language_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Updater Version: {0} - Compilation: {1}.
        /// </summary>
        public static string StrAutoUpdateVersion {
            get {
                return ResourceManager.GetString("StrAutoUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Calculating download size....
        /// </summary>
        public static string StrCalculatingDownloadSize {
            get {
                return ResourceManager.GetString("StrCalculatingDownloadSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verifying privacy terms....
        /// </summary>
        public static string StrCheckingPrivacyTerms {
            get {
                return ResourceManager.GetString("StrCheckingPrivacyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error occurred while trying to update the client, you may not be able to login..
        /// </summary>
        public static string StrClientUpdatedError {
            get {
                return ResourceManager.GetString("StrClientUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Client updated successfully! Enjoy the game!.
        /// </summary>
        public static string StrClientUpdatedOK {
            get {
                return ResourceManager.GetString("StrClientUpdatedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Closing the updater will end all connections with your servers and all your current clients will be disconnected. Without an active connection between our client and the update server you compromise your client security, then, just close the updater if you already ended all instances of the game. Are you sure you want to close the updater?.
        /// </summary>
        public static string StrCloseWindowMsg {
            get {
                return ResourceManager.GetString("StrCloseWindowMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Are you sure?.
        /// </summary>
        public static string StrCloseWindowTitle {
            get {
                return ResourceManager.GetString("StrCloseWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connecting to the server....
        /// </summary>
        public static string StrConnectingToServer {
            get {
                return ResourceManager.GetString("StrConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An error ocurred when trying to contact our servers. Try again later..
        /// </summary>
        public static string StrConnectionError {
            get {
                return ResourceManager.GetString("StrConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a An instance of the World Conquer client is already in execution. To continue installing the patches, please close all clients and press &quot;Yes&quot;. By pressing &quot;Yes&quot; if you haven&apos;t closed all instances of the game, the updater will force them to close, and this includes any Conquer client..
        /// </summary>
        public static string StrConquerRunning {
            get {
                return ResourceManager.GetString("StrConquerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Close the clients to continue.
        /// </summary>
        public static string StrConquerRunningTitle {
            get {
                return ResourceManager.GetString("StrConquerRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a We could not connect to the update server. Do you want to download the patches manually?.
        /// </summary>
        public static string StrCouldNotConnectToAutoPatch {
            get {
                return ResourceManager.GetString("StrCouldNotConnectToAutoPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connection Error.
        /// </summary>
        public static string StrCouldNotConnectToAutoPatchTitle {
            get {
                return ResourceManager.GetString("StrCouldNotConnectToAutoPatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a We were not able to connect to the update servers..
        /// </summary>
        public static string StrCouldNotFindUpdaterServer {
            get {
                return ResourceManager.GetString("StrCouldNotFindUpdaterServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a You cannot start the game if you do not accept our Privacy Terms..
        /// </summary>
        public static string StrErrorPrivacyNotAccepted {
            get {
                return ResourceManager.GetString("StrErrorPrivacyNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The file `{0}` is missing in your client folder. Verify if your client is in the final version or download the game again.está faltando no seu cliente..
        /// </summary>
        public static string StrFileMissing {
            get {
                return ResourceManager.GetString("StrFileMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a File missing.
        /// </summary>
        public static string StrFileMissingTitle {
            get {
                return ResourceManager.GetString("StrFileMissingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Version: {0}.
        /// </summary>
        public static string StrGameVersion {
            get {
                return ResourceManager.GetString("StrGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Installing patch {0}. Please wait....
        /// </summary>
        public static string StrInstallingUpdates {
            get {
                return ResourceManager.GetString("StrInstallingUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} updates will be downloaded ({1})..
        /// </summary>
        public static string StrLabelCalculatingDownloadAmount {
            get {
                return ResourceManager.GetString("StrLabelCalculatingDownloadAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Downloading update {0} of {1}. {2}/{3} ({4}).
        /// </summary>
        public static string StrLabelDownloading {
            get {
                return ResourceManager.GetString("StrLabelDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Your login has not been authorized! Your IP Address may be blocked in our servers. Please contact our client support..
        /// </summary>
        public static string StrLoginNotAllowed {
            get {
                return ResourceManager.GetString("StrLoginNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching for game updates....
        /// </summary>
        public static string StrLookingForGameUpdates {
            get {
                return ResourceManager.GetString("StrLookingForGameUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Searching for anti-cheat updates....
        /// </summary>
        public static string StrLookingForUpdaterUpdates {
            get {
                return ResourceManager.GetString("StrLookingForUpdaterUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a New updates has been found. Please, close the current clients and open the updater again..
        /// </summary>
        public static string StrNewUpdatesFound {
            get {
                return ResourceManager.GetString("StrNewUpdatesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Could not update due to running instances of the game..
        /// </summary>
        public static string StrOpenClientError {
            get {
                return ResourceManager.GetString("StrOpenClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a The updates has been installed, please wait while we check if there are more patches..
        /// </summary>
        public static string StrPatchsInstalled {
            get {
                return ResourceManager.GetString("StrPatchsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Looking for open instances of the game.
        /// </summary>
        public static string StrSearchForOpenInstances {
            get {
                return ResourceManager.GetString("StrSearchForOpenInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Preparing to install updates..
        /// </summary>
        public static string StrStartInstallUpdates {
            get {
                return ResourceManager.GetString("StrStartInstallUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a To start or continue playing you need to agree our %privacy_terms%. Please, click in the link above and read carefully, our launcher checks for all processes running in your Operating System. If you do not agree, please close our launcher and uninstall the game..
        /// </summary>
        public static string StrTermsOfPrivacyDesc {
            get {
                return ResourceManager.GetString("StrTermsOfPrivacyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Privacy Terms.
        /// </summary>
        public static string StrTermsOfPrivacyTitle {
            get {
                return ResourceManager.GetString("StrTermsOfPrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Privacy Terms.
        /// </summary>
        public static string StrTopLabel {
            get {
                return ResourceManager.GetString("StrTopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Terms of Service.
        /// </summary>
        public static string StrTosLabel {
            get {
                return ResourceManager.GetString("StrTosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Connected with success! Looking for updates..
        /// </summary>
        public static string StrUpdaterServerFound {
            get {
                return ResourceManager.GetString("StrUpdaterServerFound", resourceCulture);
            }
        }
    }
}
