//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutoUpdater {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Language_pt_BR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Language_pt_BR() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AutoUpdater.Language_pt-BR", typeof(Language_pt_BR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão do Atualizador: {0} - Compilação: {1}.
        /// </summary>
        public static string StrAutoUpdateVersion {
            get {
                return ResourceManager.GetString("StrAutoUpdateVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Verificando termos de privacidade....
        /// </summary>
        public static string StrCheckingPrivacyTerms {
            get {
                return ResourceManager.GetString("StrCheckingPrivacyTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar o cliente. Talvez você não consiga entrar no jogo..
        /// </summary>
        public static string StrClientUpdatedError {
            get {
                return ResourceManager.GetString("StrClientUpdatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Cliente atualizado com sucesso! Bom jogo..
        /// </summary>
        public static string StrClientUpdatedOK {
            get {
                return ResourceManager.GetString("StrClientUpdatedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectando-se ao servidor....
        /// </summary>
        public static string StrConnectingToServer {
            get {
                return ResourceManager.GetString("StrConnectingToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Houve um erro na conexão com o servidor. Tente novamente mais tarde..
        /// </summary>
        public static string StrConnectionError {
            get {
                return ResourceManager.GetString("StrConnectionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a O cliente do World Conquer já está em execução! Para prosseguir com a instalação dos pacotes, por favor feche os clientes que estão abertos e pressione &quot;Sim&quot;. Ao pressionar &quot;Sim&quot; o atualizador forçará o cliente de qualquer cliente do Conquer em andamento, isto inclui também versões oficiais..
        /// </summary>
        public static string StrConquerRunning {
            get {
                return ResourceManager.GetString("StrConquerRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Feche os clientes para continuar.
        /// </summary>
        public static string StrConquerRunningTitle {
            get {
                return ResourceManager.GetString("StrConquerRunningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível conectar-se ao servidor de atualizações. Deseja baixar manualmente as atualizações?.
        /// </summary>
        public static string StrCouldNotConnectToAutoPatch {
            get {
                return ResourceManager.GetString("StrCouldNotConnectToAutoPatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Erro de conexão.
        /// </summary>
        public static string StrCouldNotConnectToAutoPatchTitle {
            get {
                return ResourceManager.GetString("StrCouldNotConnectToAutoPatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível se conectar ao servidor do atualizador..
        /// </summary>
        public static string StrCouldNotFindUpdaterServer {
            get {
                return ResourceManager.GetString("StrCouldNotFindUpdaterServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Você não pode atualizar ou iniciar o jogo sem aceitar os termos de privacidade..
        /// </summary>
        public static string StrErrorPrivacyNotAccepted {
            get {
                return ResourceManager.GetString("StrErrorPrivacyNotAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Versão: {0}.
        /// </summary>
        public static string StrGameVersion {
            get {
                return ResourceManager.GetString("StrGameVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Não foi possível atualizar devido a instâncias do cliente do jogo em aberto..
        /// </summary>
        public static string StrOpenClientError {
            get {
                return ResourceManager.GetString("StrOpenClientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Procurando por instâncias do jogo em aberto.
        /// </summary>
        public static string StrSearchForOpenInstances {
            get {
                return ResourceManager.GetString("StrSearchForOpenInstances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Para começar ou continuar a jogar você deve aceitar nossos %privacy_terms%. 
        ///Por favor clique no link acima e leia cuidadosamente, nosso Launcher realiza uma varredura pelos processos em seu sistema operacional. Se você não concorda, por favor feche o inicializador e desinstale o jogo..
        /// </summary>
        public static string StrTermsOfPrivacyDesc {
            get {
                return ResourceManager.GetString("StrTermsOfPrivacyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Termos de Privacidade.
        /// </summary>
        public static string StrTermsOfPrivacyTitle {
            get {
                return ResourceManager.GetString("StrTermsOfPrivacyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Termos de Privacidade.
        /// </summary>
        public static string StrTopLabel {
            get {
                return ResourceManager.GetString("StrTopLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Termos de Serviço.
        /// </summary>
        public static string StrTosLabel {
            get {
                return ResourceManager.GetString("StrTosLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Conectado com sucesso! Procurando por atualizações..
        /// </summary>
        public static string StrUpdaterServerFound {
            get {
                return ResourceManager.GetString("StrUpdaterServerFound", resourceCulture);
            }
        }
    }
}
